### ISSUE TITLE
Do not recognize :has rules as extended CSS with Safari 15.4 or newer

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/SafariConverterLib#39] opened 2022-08-24 15:07 UTC
Since it is now natively supported we should change the ExtCSS detection rules and not detect `:has` rules as extended:
https://caniuse.com/css-has

But only when Safari 15.4.

**Comment by maximtop** [comment] 2023-07-04 12:41
Was fixed in
https://github.com/AdguardTeam/SafariConverterLib/commit/8ebe6e99b9acfd551f8236d2d4d2b6054c91b793#diff-5229a20bc3b68bb011ace064e0ec399dd078584575909e533234f4f09e1e6478R127

**Closed** 2023-07-04 12:41 UTC
Labels: enhancement, Status: Resolved, Resolution: Duplicate, Priority: P4

**Comment by krystian3w** [comment] 2023-07-04 13:17
Similar should be Chromium 105+ to avoid favor only Safari. Rather, no one spends time there for a better implementation (for example, only the 120+ edition should be considered similar in terms of performance to Safari). . 

Moz://a have plans unlock in next month at 116 stable release (as long as they have enough programmers' processing power to release an efficient version and not a buggy one).
